site_name: Python Template
repo_url: https://github.com/Zovi343/python_template
repo_name: python_template

nav:
  - Home: index.md
  - Usage: usage.md

theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true